# Main Configs
url: https://tongai-zinaka.github.io
title: Tongai Zinaka
email: tongaizinaka@gmail.com
author: Tongai Zinaka
description: > # Write an awesome description for your new site here.
  Data & Business Intelligence Analyst specializing in Power BI, SQL, and data modeling. 
  I transform complex data into actionable insights that drive strategic business decisions.

# Head meta for Google search results
copyright: 'Copyright &copy; 2025 Tongai Zinaka. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# Jekyll & Plugins
markdown: kramdown
permalink: pretty

# 3rd Party Settings
social:
  - title: linkedin
    url: https://www.linkedin.com/in/tongai-zinaka/
  - title: github
    url: https://github.com/tongai-zinaka
