#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Tongai Zinaka | Data and Business Analyst

# Short bio or description (displayed in the header)
description: Data & Business Intelligence Analyst

# URL of your avatar or profile pic. Upload your cropped graphic to the 'img' folder and update this link.
avatar: https://raw.githubusercontent.com/Tongai-Zinaka/tongai-zinaka.github.io/main/img/profile-graphic.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: tongaizinaka@gmail.com
  facebook:
  flickr:
  github: tongai-zinaka
  instagram:
  linkedin: tongai-zinaka
  pinterest:
  rss: 
  twitter:
  stackoverflow: 
  youtube:
  googleplus:


# Enter your Disqus shortname for commenting on posts
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://tongai-zinaka.github.io

# You don't need to change any of the configuration flags below!
#
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
